name: finolytica
description: "Akıllı Finans Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
    
  flutter_dotenv: ^5.1.0
  
  http: ^1.2.1 
  cupertino_icons: ^1.0.8
  # State Management
  get: ^4.6.6
  
  provider: ^6.0.5

  # Backend
  supabase_flutter: ^2.9.1
  url_launcher: ^6.2.1
  
  # UI & Animations
  getwidget: ^4.0.0
  velocity_x: ^4.2.1
  flutter_neumorphic_plus: ^3.3.0
  lottie: ^3.1.3
  fl_chart: ^0.70.1
  
  # Utilities
  intl: ^0.20.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  local_auth: ^2.3.0
  
  # Icons & Fonts
  google_fonts: ^6.2.1
  
  # Desktop Window Management & Device Preview
  window_manager: ^0.3.7
  device_preview: ^1.1.0

  # Analytics & Export için
  pdf: ^3.11.1
  path_provider: ^2.1.4
  excel: ^4.0.6
  share_plus: ^10.0.2

  # YENİ: Investment özellikleri için eklenenler
  flutter_datetime_picker: ^1.5.1  # Tarih seçici
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets: 
    - .env    
    - assets/images/
    - assets/icons/
    - assets/animations/